apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello-skq1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello-skq1
    app.kubernetes.io/part-of: common-nodejs-parent
  name: node-express-hello-skq1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-express-hello-skq1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: node-express-hello-skq1
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/common-nodejs-parent/node-express-hello-skq1@sha256:2d09f0acc39e7b9896cf2f60511214069629bd13705f45696afdc8982eb54213
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
