apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello-skq1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello-skq1
    app.kubernetes.io/part-of: common-nodejs-parent
  name: node-express-hello-skq1
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: node-express-hello-skq1
status:
  loadBalancer: {}
