apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: testsample-go-lunn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testsample-go-lunn
    app.kubernetes.io/part-of: common-nodejs-parent
  name: testsample-go-lunn3utj
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testsample-go-lunn
    weight: 100
status: {}
