apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: common-nodejs-parent
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: common-nodejs-parent
    app.kubernetes.io/part-of: common-nodejs-parent
  name: common-nodejs-parent
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: common-nodejs-parent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: common-nodejs-parent
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/common-nodejs-parent/common-nodejs-parent@sha256:2ae149d8d03bb21f7c8ca6ca0a828ebe06b1fe8365ba05c31c8050d6cf7ecec1
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
