apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: common-nodejs-parent
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: common-nodejs-parent
    app.kubernetes.io/part-of: common-nodejs-parent
  name: common-nodejs-parent
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: common-nodejs-parent
status:
  loadBalancer: {}
