apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello-skq1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello-skq1
    app.kubernetes.io/part-of: common-nodejs-parent
  name: node-express-hello-skq1tejx
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: node-express-hello-skq1
    weight: 100
status: {}
